# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'insitu_ECHO_GUI_2.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(605, 879)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_12 = QtGui.QGridLayout(self.tab)
        self.gridLayout_12.setMargin(0)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_21 = QtGui.QLabel(self.tab)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_6.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self.tab)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_6.addWidget(self.label_23, 2, 0, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.tab)
        self.lineEdit_2.setText(_fromUtf8(""))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_6.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.tab)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_6.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lineEditSave = QtGui.QLineEdit(self.tab)
        self.lineEditSave.setText(_fromUtf8(""))
        self.lineEditSave.setReadOnly(False)
        self.lineEditSave.setObjectName(_fromUtf8("lineEditSave"))
        self.gridLayout_2.addWidget(self.lineEditSave, 0, 0, 1, 1)
        self.checkBoxSave = QtGui.QCheckBox(self.tab)
        self.checkBoxSave.setChecked(True)
        self.checkBoxSave.setObjectName(_fromUtf8("checkBoxSave"))
        self.gridLayout_2.addWidget(self.checkBoxSave, 0, 2, 1, 1)
        self.pushButtonSave = QtGui.QPushButton(self.tab)
        self.pushButtonSave.setObjectName(_fromUtf8("pushButtonSave"))
        self.gridLayout_2.addWidget(self.pushButtonSave, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_2, 3, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.tab)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_6.addWidget(self.label_24, 3, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_6, 1, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_15 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.comboBox_Measurement = QtGui.QComboBox(self.groupBox)
        self.comboBox_Measurement.setObjectName(_fromUtf8("comboBox_Measurement"))
        self.comboBox_Measurement.addItem(_fromUtf8(""))
        self.comboBox_Measurement.addItem(_fromUtf8(""))
        self.comboBox_Measurement.addItem(_fromUtf8(""))
        self.comboBox_Measurement.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.comboBox_Measurement)
        self.stackedWidget = QtGui.QStackedWidget(self.groupBox)
        self.stackedWidget.setFrameShape(QtGui.QFrame.StyledPanel)
        self.stackedWidget.setFrameShadow(QtGui.QFrame.Sunken)
        self.stackedWidget.setLineWidth(2)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page_IVmeas = QtGui.QWidget()
        self.page_IVmeas.setObjectName(_fromUtf8("page_IVmeas"))
        self.gridLayout_16 = QtGui.QGridLayout(self.page_IVmeas)
        self.gridLayout_16.setMargin(0)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_7 = QtGui.QLabel(self.page_IVmeas)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_4.addWidget(self.label_7)
        self.checkBox_IV = QtGui.QCheckBox(self.page_IVmeas)
        self.checkBox_IV.setChecked(False)
        self.checkBox_IV.setObjectName(_fromUtf8("checkBox_IV"))
        self.verticalLayout_4.addWidget(self.checkBox_IV)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_11 = QtGui.QLabel(self.page_IVmeas)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_4.addWidget(self.label_11, 1, 3, 1, 1)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.page_IVmeas)
        self.doubleSpinBox.setSuffix(_fromUtf8(""))
        self.doubleSpinBox.setDecimals(1)
        self.doubleSpinBox.setMinimum(-999.0)
        self.doubleSpinBox.setMaximum(0.0)
        self.doubleSpinBox.setProperty("value", -10.0)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.gridLayout_4.addWidget(self.doubleSpinBox, 0, 1, 1, 1)
        self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(self.page_IVmeas)
        self.doubleSpinBox_3.setDecimals(3)
        self.doubleSpinBox_3.setMinimum(0.0)
        self.doubleSpinBox_3.setMaximum(5.0)
        self.doubleSpinBox_3.setSingleStep(0.5)
        self.doubleSpinBox_3.setProperty("value", 0.5)
        self.doubleSpinBox_3.setObjectName(_fromUtf8("doubleSpinBox_3"))
        self.gridLayout_4.addWidget(self.doubleSpinBox_3, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.page_IVmeas)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.page_IVmeas)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_4.addWidget(self.label_10, 1, 0, 1, 1)
        self.doubleSpinBox_4 = QtGui.QDoubleSpinBox(self.page_IVmeas)
        self.doubleSpinBox_4.setSuffix(_fromUtf8(""))
        self.doubleSpinBox_4.setDecimals(2)
        self.doubleSpinBox_4.setMaximum(60.0)
        self.doubleSpinBox_4.setSingleStep(0.1)
        self.doubleSpinBox_4.setProperty("value", 0.1)
        self.doubleSpinBox_4.setObjectName(_fromUtf8("doubleSpinBox_4"))
        self.gridLayout_4.addWidget(self.doubleSpinBox_4, 1, 4, 1, 1)
        self.label_9 = QtGui.QLabel(self.page_IVmeas)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 0, 3, 1, 1)
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.page_IVmeas)
        self.doubleSpinBox_2.setSuffix(_fromUtf8(""))
        self.doubleSpinBox_2.setDecimals(1)
        self.doubleSpinBox_2.setMaximum(999.0)
        self.doubleSpinBox_2.setProperty("value", 10.0)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.gridLayout_4.addWidget(self.doubleSpinBox_2, 0, 4, 1, 1)
        self.initialV_units = QtGui.QComboBox(self.page_IVmeas)
        self.initialV_units.setObjectName(_fromUtf8("initialV_units"))
        self.initialV_units.addItem(_fromUtf8(""))
        self.initialV_units.addItem(_fromUtf8(""))
        self.initialV_units.addItem(_fromUtf8(""))
        self.initialV_units.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.initialV_units, 0, 2, 1, 1)
        self.stepV_units = QtGui.QComboBox(self.page_IVmeas)
        self.stepV_units.setObjectName(_fromUtf8("stepV_units"))
        self.stepV_units.addItem(_fromUtf8(""))
        self.stepV_units.addItem(_fromUtf8(""))
        self.stepV_units.addItem(_fromUtf8(""))
        self.stepV_units.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.stepV_units, 1, 2, 1, 1)
        self.finalV_units = QtGui.QComboBox(self.page_IVmeas)
        self.finalV_units.setObjectName(_fromUtf8("finalV_units"))
        self.finalV_units.addItem(_fromUtf8(""))
        self.finalV_units.addItem(_fromUtf8(""))
        self.finalV_units.addItem(_fromUtf8(""))
        self.finalV_units.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.finalV_units, 0, 5, 1, 1)
        self.holdtime_units = QtGui.QComboBox(self.page_IVmeas)
        self.holdtime_units.setObjectName(_fromUtf8("holdtime_units"))
        self.holdtime_units.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.holdtime_units, 1, 5, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_4)
        self.gridLayout_16.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_6 = QtGui.QLabel(self.page_IVmeas)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_3.addWidget(self.label_6)
        self.checkBox_fixedV = QtGui.QCheckBox(self.page_IVmeas)
        self.checkBox_fixedV.setChecked(False)
        self.checkBox_fixedV.setObjectName(_fromUtf8("checkBox_fixedV"))
        self.verticalLayout_3.addWidget(self.checkBox_fixedV)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_3 = QtGui.QLabel(self.page_IVmeas)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 3, 0, 1, 1)
        self.spinBox_nRepeats = QtGui.QSpinBox(self.page_IVmeas)
        self.spinBox_nRepeats.setMaximum(1000)
        self.spinBox_nRepeats.setProperty("value", 20)
        self.spinBox_nRepeats.setObjectName(_fromUtf8("spinBox_nRepeats"))
        self.gridLayout_3.addWidget(self.spinBox_nRepeats, 2, 1, 1, 1)
        self.doubleSpinBox_Voltage = QtGui.QDoubleSpinBox(self.page_IVmeas)
        self.doubleSpinBox_Voltage.setSuffix(_fromUtf8(""))
        self.doubleSpinBox_Voltage.setDecimals(1)
        self.doubleSpinBox_Voltage.setMaximum(100.0)
        self.doubleSpinBox_Voltage.setProperty("value", 1.0)
        self.doubleSpinBox_Voltage.setObjectName(_fromUtf8("doubleSpinBox_Voltage"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_Voltage, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.page_IVmeas)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.page_IVmeas)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.doubleSpinBox_pauseTime = QtGui.QDoubleSpinBox(self.page_IVmeas)
        self.doubleSpinBox_pauseTime.setSuffix(_fromUtf8(""))
        self.doubleSpinBox_pauseTime.setDecimals(1)
        self.doubleSpinBox_pauseTime.setMaximum(1000.0)
        self.doubleSpinBox_pauseTime.setProperty("value", 0.5)
        self.doubleSpinBox_pauseTime.setObjectName(_fromUtf8("doubleSpinBox_pauseTime"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_pauseTime, 3, 1, 1, 1)
        self.fixedV_units = QtGui.QComboBox(self.page_IVmeas)
        self.fixedV_units.setObjectName(_fromUtf8("fixedV_units"))
        self.fixedV_units.addItem(_fromUtf8(""))
        self.fixedV_units.addItem(_fromUtf8(""))
        self.fixedV_units.addItem(_fromUtf8(""))
        self.fixedV_units.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.fixedV_units, 1, 2, 1, 1)
        self.fixedV_pausetime_units = QtGui.QComboBox(self.page_IVmeas)
        self.fixedV_pausetime_units.setObjectName(_fromUtf8("fixedV_pausetime_units"))
        self.fixedV_pausetime_units.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.fixedV_pausetime_units, 3, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.gridLayout_16.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_16 = QtGui.QLabel(self.page_IVmeas)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_9.addWidget(self.label_16)
        self.checkBox_fixedI = QtGui.QCheckBox(self.page_IVmeas)
        self.checkBox_fixedI.setChecked(False)
        self.checkBox_fixedI.setObjectName(_fromUtf8("checkBox_fixedI"))
        self.verticalLayout_9.addWidget(self.checkBox_fixedI)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.doubleSpinBox_Voltage_2 = QtGui.QDoubleSpinBox(self.page_IVmeas)
        self.doubleSpinBox_Voltage_2.setSuffix(_fromUtf8(""))
        self.doubleSpinBox_Voltage_2.setDecimals(1)
        self.doubleSpinBox_Voltage_2.setMaximum(100.0)
        self.doubleSpinBox_Voltage_2.setProperty("value", 1.0)
        self.doubleSpinBox_Voltage_2.setObjectName(_fromUtf8("doubleSpinBox_Voltage_2"))
        self.gridLayout_10.addWidget(self.doubleSpinBox_Voltage_2, 1, 1, 1, 1)
        self.spinBox_nRepeats_2 = QtGui.QSpinBox(self.page_IVmeas)
        self.spinBox_nRepeats_2.setMaximum(1000)
        self.spinBox_nRepeats_2.setProperty("value", 20)
        self.spinBox_nRepeats_2.setObjectName(_fromUtf8("spinBox_nRepeats_2"))
        self.gridLayout_10.addWidget(self.spinBox_nRepeats_2, 2, 1, 1, 1)
        self.doubleSpinBox_pauseTime_2 = QtGui.QDoubleSpinBox(self.page_IVmeas)
        self.doubleSpinBox_pauseTime_2.setSuffix(_fromUtf8(""))
        self.doubleSpinBox_pauseTime_2.setDecimals(1)
        self.doubleSpinBox_pauseTime_2.setMaximum(1000.0)
        self.doubleSpinBox_pauseTime_2.setProperty("value", 0.5)
        self.doubleSpinBox_pauseTime_2.setObjectName(_fromUtf8("doubleSpinBox_pauseTime_2"))
        self.gridLayout_10.addWidget(self.doubleSpinBox_pauseTime_2, 3, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.page_IVmeas)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_10.addWidget(self.label_31, 3, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.page_IVmeas)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_10.addWidget(self.label_27, 1, 0, 1, 1)
        self.label_30 = QtGui.QLabel(self.page_IVmeas)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_10.addWidget(self.label_30, 2, 0, 1, 1)
        self.fixedI_units = QtGui.QComboBox(self.page_IVmeas)
        self.fixedI_units.setObjectName(_fromUtf8("fixedI_units"))
        self.fixedI_units.addItem(_fromUtf8(""))
        self.fixedI_units.addItem(_fromUtf8(""))
        self.fixedI_units.addItem(_fromUtf8(""))
        self.fixedI_units.addItem(_fromUtf8(""))
        self.gridLayout_10.addWidget(self.fixedI_units, 1, 2, 1, 1)
        self.fixedI_pausetime_units = QtGui.QComboBox(self.page_IVmeas)
        self.fixedI_pausetime_units.setObjectName(_fromUtf8("fixedI_pausetime_units"))
        self.fixedI_pausetime_units.addItem(_fromUtf8(""))
        self.gridLayout_10.addWidget(self.fixedI_pausetime_units, 3, 2, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_10)
        self.gridLayout_16.addLayout(self.verticalLayout_9, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_IVmeas)
        self.page_keithley = QtGui.QWidget()
        self.page_keithley.setObjectName(_fromUtf8("page_keithley"))
        self.gridLayout_17 = QtGui.QGridLayout(self.page_keithley)
        self.gridLayout_17.setMargin(0)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_22 = QtGui.QLabel(self.page_keithley)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout_5.addWidget(self.label_22)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_12 = QtGui.QLabel(self.page_keithley)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_5.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.page_keithley)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_5.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.page_keithley)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_5.addWidget(self.label_14, 3, 0, 1, 1)
        self.comboBox_3 = QtGui.QComboBox(self.page_keithley)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.comboBox_3, 2, 1, 1, 1)
        self.comboBox = QtGui.QComboBox(self.page_keithley)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.comboBox, 0, 1, 1, 1)
        self.comboBox_4 = QtGui.QComboBox(self.page_keithley)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.comboBox_4, 3, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.page_keithley)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_5.addWidget(self.label_15, 1, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.page_keithley)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_5.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_5)
        self.label_20 = QtGui.QLabel(self.page_keithley)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_5.addWidget(self.label_20)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.comboBox_7 = QtGui.QComboBox(self.page_keithley)
        self.comboBox_7.setObjectName(_fromUtf8("comboBox_7"))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.comboBox_7.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.comboBox_7, 1, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.page_keithley)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_7.addWidget(self.label_25, 3, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.page_keithley)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_7.addWidget(self.label_18, 1, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.page_keithley)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_7.addWidget(self.label_17, 0, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.page_keithley)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_7.addWidget(self.label_19, 2, 0, 1, 1)
        self.comboBox_6 = QtGui.QComboBox(self.page_keithley)
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.comboBox_6.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.comboBox_6, 0, 1, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.page_keithley)
        self.spinBox.setMinimum(-9)
        self.spinBox.setMaximum(1)
        self.spinBox.setProperty("value", -3)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout_7.addWidget(self.spinBox, 3, 1, 1, 1)
        self.comboBox_8 = QtGui.QComboBox(self.page_keithley)
        self.comboBox_8.setEditable(True)
        self.comboBox_8.setObjectName(_fromUtf8("comboBox_8"))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.comboBox_8.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.comboBox_8, 2, 1, 1, 1)
        self.label_32 = QtGui.QLabel(self.page_keithley)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_7.addWidget(self.label_32, 4, 0, 1, 1)
        self.spinBox_2 = QtGui.QSpinBox(self.page_keithley)
        self.spinBox_2.setMinimum(-6)
        self.spinBox_2.setMaximum(2)
        self.spinBox_2.setProperty("value", 0)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.gridLayout_7.addWidget(self.spinBox_2, 4, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_7)
        self.gridLayout_17.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_keithley)
        self.page_deposition = QtGui.QWidget()
        self.page_deposition.setObjectName(_fromUtf8("page_deposition"))
        self.gridLayout_18 = QtGui.QGridLayout(self.page_deposition)
        self.gridLayout_18.setMargin(0)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_26 = QtGui.QLabel(self.page_deposition)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_8.addWidget(self.label_26, 1, 0, 1, 1)
        self.doubleSpinBox_5 = QtGui.QDoubleSpinBox(self.page_deposition)
        self.doubleSpinBox_5.setDecimals(1)
        self.doubleSpinBox_5.setMaximum(60.0)
        self.doubleSpinBox_5.setProperty("value", 1.0)
        self.doubleSpinBox_5.setObjectName(_fromUtf8("doubleSpinBox_5"))
        self.gridLayout_8.addWidget(self.doubleSpinBox_5, 1, 1, 1, 1)
        self.label_33 = QtGui.QLabel(self.page_deposition)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_8.addWidget(self.label_33, 0, 0, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.page_deposition)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout_8.addWidget(self.lineEdit_4, 0, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_8)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_8.addItem(spacerItem1)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_29 = QtGui.QLabel(self.page_deposition)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_9.addWidget(self.label_29, 0, 0, 1, 1)
        self.checkBoxQCM1 = QtGui.QCheckBox(self.page_deposition)
        self.checkBoxQCM1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBoxQCM1.setAutoFillBackground(False)
        self.checkBoxQCM1.setChecked(True)
        self.checkBoxQCM1.setObjectName(_fromUtf8("checkBoxQCM1"))
        self.gridLayout_9.addWidget(self.checkBoxQCM1, 0, 1, 1, 1)
        self.checkBoxQCM2 = QtGui.QCheckBox(self.page_deposition)
        self.checkBoxQCM2.setChecked(True)
        self.checkBoxQCM2.setObjectName(_fromUtf8("checkBoxQCM2"))
        self.gridLayout_9.addWidget(self.checkBoxQCM2, 1, 1, 1, 1)
        self.checkBoxQCM3 = QtGui.QCheckBox(self.page_deposition)
        self.checkBoxQCM3.setObjectName(_fromUtf8("checkBoxQCM3"))
        self.gridLayout_9.addWidget(self.checkBoxQCM3, 2, 1, 1, 1)
        self.checkBoxQCM4 = QtGui.QCheckBox(self.page_deposition)
        self.checkBoxQCM4.setObjectName(_fromUtf8("checkBoxQCM4"))
        self.gridLayout_9.addWidget(self.checkBoxQCM4, 3, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_9)
        self.gridLayout_18.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_deposition)
        self.Substrate_page = QtGui.QWidget()
        self.Substrate_page.setObjectName(_fromUtf8("Substrate_page"))
        self.gridLayout_19 = QtGui.QGridLayout(self.Substrate_page)
        self.gridLayout_19.setMargin(0)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.label_5 = QtGui.QLabel(self.Substrate_page)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_19.addWidget(self.label_5, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.Substrate_page)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.gridLayout_15.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_14 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_14.setMargin(0)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.label_4 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_14.addWidget(self.label_4, 2, 0, 1, 1)
        self.comboBoxQCM_Display = QtGui.QComboBox(self.tab_3)
        self.comboBoxQCM_Display.setObjectName(_fromUtf8("comboBoxQCM_Display"))
        self.comboBoxQCM_Display.addItem(_fromUtf8(""))
        self.comboBoxQCM_Display.addItem(_fromUtf8(""))
        self.gridLayout_14.addWidget(self.comboBoxQCM_Display, 6, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_QCMStart = QtGui.QPushButton(self.tab_3)
        self.pushButton_QCMStart.setObjectName(_fromUtf8("pushButton_QCMStart"))
        self.horizontalLayout_2.addWidget(self.pushButton_QCMStart)
        self.pushButton_QCMStop = QtGui.QPushButton(self.tab_3)
        self.pushButton_QCMStop.setObjectName(_fromUtf8("pushButton_QCMStop"))
        self.horizontalLayout_2.addWidget(self.pushButton_QCMStop)
        self.gridLayout_14.addLayout(self.horizontalLayout_2, 9, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_20 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.plainTextEdit_2 = QtGui.QPlainTextEdit(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.plainTextEdit_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.plainTextEdit_2.setObjectName(_fromUtf8("plainTextEdit_2"))
        self.gridLayout_20.addWidget(self.plainTextEdit_2, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_3, 8, 0, 1, 1)
        self.plotLayout_2 = QtGui.QVBoxLayout()
        self.plotLayout_2.setObjectName(_fromUtf8("plotLayout_2"))
        self.pltWidget_2 = MatplotlibWidget(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pltWidget_2.sizePolicy().hasHeightForWidth())
        self.pltWidget_2.setSizePolicy(sizePolicy)
        self.pltWidget_2.setObjectName(_fromUtf8("pltWidget_2"))
        self.plotLayout_2.addWidget(self.pltWidget_2)
        self.gridLayout_14.addLayout(self.plotLayout_2, 7, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_11 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_11.setMargin(0)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.metalButton = QtGui.QPushButton(self.tab_4)
        self.metalButton.setObjectName(_fromUtf8("metalButton"))
        self.verticalLayout_6.addWidget(self.metalButton)
        self.gridLayout_21 = QtGui.QGridLayout()
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.lcdPressure = QtGui.QLCDNumber(self.tab_4)
        self.lcdPressure.setObjectName(_fromUtf8("lcdPressure"))
        self.gridLayout_21.addWidget(self.lcdPressure, 1, 1, 1, 1)
        self.lcdPower = QtGui.QLCDNumber(self.tab_4)
        self.lcdPower.setObjectName(_fromUtf8("lcdPower"))
        self.gridLayout_21.addWidget(self.lcdPower, 2, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.tab_4)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_21.addWidget(self.label_28, 2, 0, 1, 1)
        self.label_34 = QtGui.QLabel(self.tab_4)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_21.addWidget(self.label_34, 1, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_21)
        self.gridLayout_11.addLayout(self.verticalLayout_6, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.plotLayout = QtGui.QVBoxLayout()
        self.plotLayout.setObjectName(_fromUtf8("plotLayout"))
        self.pltWidget = MatplotlibWidget(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pltWidget.sizePolicy().hasHeightForWidth())
        self.pltWidget.setSizePolicy(sizePolicy)
        self.pltWidget.setObjectName(_fromUtf8("pltWidget"))
        self.plotLayout.addWidget(self.pltWidget)
        self.verticalLayout.addLayout(self.plotLayout)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.plainTextEdit.setFrameShape(QtGui.QFrame.NoFrame)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.gridLayout_13.addWidget(self.plainTextEdit, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.stop_button = QtGui.QPushButton(self.tab_2)
        self.stop_button.setObjectName(_fromUtf8("stop_button"))
        self.gridLayout.addWidget(self.stop_button, 0, 1, 1, 1)
        self.start_button = QtGui.QPushButton(self.tab_2)
        self.start_button.setObjectName(_fromUtf8("start_button"))
        self.gridLayout.addWidget(self.start_button, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 605, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_settings = QtGui.QAction(MainWindow)
        self.actionSave_settings.setObjectName(_fromUtf8("actionSave_settings"))
        self.actionLoad_settings = QtGui.QAction(MainWindow)
        self.actionLoad_settings.setObjectName(_fromUtf8("actionLoad_settings"))
        self.actionContact_Ross = QtGui.QAction(MainWindow)
        self.actionContact_Ross.setObjectName(_fromUtf8("actionContact_Ross"))
        self.menuFile.addAction(self.actionSave_settings)
        self.menuFile.addAction(self.actionLoad_settings)
        self.menuHelp.addAction(self.actionContact_Ross)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_Measurement.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(2)
        self.fixedI_units.setCurrentIndex(2)
        self.comboBox_8.setCurrentIndex(2)
        QtCore.QObject.connect(self.comboBox_Measurement, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ECHO monitor", None))
        self.label_21.setText(_translate("MainWindow", "Experiment Name", None))
        self.label_23.setText(_translate("MainWindow", "Sample", None))
        self.lineEdit_2.setAccessibleName(_translate("MainWindow", "exp_name", None))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "< Type of Measurement >", None))
        self.lineEdit_3.setAccessibleName(_translate("MainWindow", "sample", None))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "< Sample name >", None))
        self.lineEditSave.setAccessibleName(_translate("MainWindow", "sav_loc", None))
        self.lineEditSave.setPlaceholderText(_translate("MainWindow", "<save directory>", None))
        self.checkBoxSave.setAccessibleName(_translate("MainWindow", "saveData", None))
        self.checkBoxSave.setText(_translate("MainWindow", "Save data", None))
        self.pushButtonSave.setText(_translate("MainWindow", "Browse", None))
        self.label_24.setText(_translate("MainWindow", "Save Location", None))
        self.groupBox.setTitle(_translate("MainWindow", "Measurement Controls", None))
        self.comboBox_Measurement.setItemText(0, _translate("MainWindow", "Deposition Controller", None))
        self.comboBox_Measurement.setItemText(1, _translate("MainWindow", "Electical Measurements", None))
        self.comboBox_Measurement.setItemText(2, _translate("MainWindow", "Keithley Setup", None))
        self.comboBox_Measurement.setItemText(3, _translate("MainWindow", "Substrate Heating Control", None))
        self.label_7.setText(_translate("MainWindow", "IV Sweep", None))
        self.checkBox_IV.setAccessibleName(_translate("MainWindow", "takeIVsweep", None))
        self.checkBox_IV.setText(_translate("MainWindow", "Take an IV sweep?", None))
        self.label_11.setText(_translate("MainWindow", "Step Time", None))
        self.doubleSpinBox.setAccessibleName(_translate("MainWindow", "initialV", None))
        self.doubleSpinBox_3.setAccessibleName(_translate("MainWindow", "stepSize", None))
        self.label_8.setText(_translate("MainWindow", "Initial Voltage", None))
        self.label_10.setAccessibleName(_translate("MainWindow", "Vstep", None))
        self.label_10.setText(_translate("MainWindow", "Voltage Step", None))
        self.doubleSpinBox_4.setAccessibleName(_translate("MainWindow", "holdTime", None))
        self.label_9.setText(_translate("MainWindow", "Final Voltage", None))
        self.doubleSpinBox_2.setAccessibleName(_translate("MainWindow", "finalV", None))
        self.initialV_units.setAccessibleName(_translate("MainWindow", "initialV_units", None))
        self.initialV_units.setItemText(0, _translate("MainWindow", "V", None))
        self.initialV_units.setItemText(1, _translate("MainWindow", "mV", None))
        self.initialV_units.setItemText(2, _translate("MainWindow", "uV", None))
        self.initialV_units.setItemText(3, _translate("MainWindow", "nV", None))
        self.stepV_units.setAccessibleName(_translate("MainWindow", "stepV_units", None))
        self.stepV_units.setItemText(0, _translate("MainWindow", "V", None))
        self.stepV_units.setItemText(1, _translate("MainWindow", "mV", None))
        self.stepV_units.setItemText(2, _translate("MainWindow", "uV", None))
        self.stepV_units.setItemText(3, _translate("MainWindow", "nV", None))
        self.finalV_units.setAccessibleName(_translate("MainWindow", "finalV_units", None))
        self.finalV_units.setItemText(0, _translate("MainWindow", "V", None))
        self.finalV_units.setItemText(1, _translate("MainWindow", "mV", None))
        self.finalV_units.setItemText(2, _translate("MainWindow", "uV", None))
        self.finalV_units.setItemText(3, _translate("MainWindow", "nV", None))
        self.holdtime_units.setAccessibleName(_translate("MainWindow", "holdtime_units", None))
        self.holdtime_units.setItemText(0, _translate("MainWindow", "seconds", None))
        self.label_6.setText(_translate("MainWindow", "Source Voltage", None))
        self.checkBox_fixedV.setAccessibleName(_translate("MainWindow", "takefixedV", None))
        self.checkBox_fixedV.setText(_translate("MainWindow", "Take fixed VOLTAGE measurements?", None))
        self.label_3.setText(_translate("MainWindow", "Pause Time", None))
        self.spinBox_nRepeats.setAccessibleName(_translate("MainWindow", "nRepeatsV", None))
        self.doubleSpinBox_Voltage.setAccessibleName(_translate("MainWindow", "fixedV", None))
        self.label.setText(_translate("MainWindow", "Voltage", None))
        self.label_2.setText(_translate("MainWindow", "Number of measurements", None))
        self.doubleSpinBox_pauseTime.setAccessibleName(_translate("MainWindow", "pauseTimeV", None))
        self.fixedV_units.setAccessibleName(_translate("MainWindow", "fixedV_units", None))
        self.fixedV_units.setItemText(0, _translate("MainWindow", "V", None))
        self.fixedV_units.setItemText(1, _translate("MainWindow", "mV", None))
        self.fixedV_units.setItemText(2, _translate("MainWindow", "uV", None))
        self.fixedV_units.setItemText(3, _translate("MainWindow", "nV", None))
        self.fixedV_pausetime_units.setAccessibleName(_translate("MainWindow", "fixedV_pausetime_units", None))
        self.fixedV_pausetime_units.setItemText(0, _translate("MainWindow", "seconds", None))
        self.label_16.setText(_translate("MainWindow", "Source Current", None))
        self.checkBox_fixedI.setAccessibleName(_translate("MainWindow", "takefixedI", None))
        self.checkBox_fixedI.setText(_translate("MainWindow", "Take fixed CURRENT measurements?", None))
        self.doubleSpinBox_Voltage_2.setAccessibleName(_translate("MainWindow", "fixedI", None))
        self.spinBox_nRepeats_2.setAccessibleName(_translate("MainWindow", "nRepeatsI", None))
        self.doubleSpinBox_pauseTime_2.setAccessibleName(_translate("MainWindow", "pauseTimeI", None))
        self.label_31.setText(_translate("MainWindow", "Pause Time", None))
        self.label_27.setText(_translate("MainWindow", "Amps", None))
        self.label_30.setText(_translate("MainWindow", "Number of measurements", None))
        self.fixedI_units.setAccessibleName(_translate("MainWindow", "fixedI_units", None))
        self.fixedI_units.setItemText(0, _translate("MainWindow", "A", None))
        self.fixedI_units.setItemText(1, _translate("MainWindow", "mA", None))
        self.fixedI_units.setItemText(2, _translate("MainWindow", "uA", None))
        self.fixedI_units.setItemText(3, _translate("MainWindow", "nA", None))
        self.fixedI_pausetime_units.setAccessibleName(_translate("MainWindow", "fixedI_pausetime_units", None))
        self.fixedI_pausetime_units.setItemText(0, _translate("MainWindow", "seconds", None))
        self.label_22.setText(_translate("MainWindow", "Connection", None))
        self.label_12.setText(_translate("MainWindow", "Connection type", None))
        self.label_13.setText(_translate("MainWindow", "Baud Rate", None))
        self.label_14.setText(_translate("MainWindow", "Term Character", None))
        self.comboBox_3.setAccessibleName(_translate("MainWindow", "baudR", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "57600", None))
        self.comboBox.setAccessibleName(_translate("MainWindow", "connectionType", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "Serial", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "GPIB", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "Other", None))
        self.comboBox_4.setAccessibleName(_translate("MainWindow", "termChar", None))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "\\r", None))
        self.label_15.setText(_translate("MainWindow", "Address", None))
        self.lineEdit.setAccessibleName(_translate("MainWindow", "connectionAddr", None))
        self.lineEdit.setText(_translate("MainWindow", "/dev/ttyUSB0", None))
        self.label_20.setText(_translate("MainWindow", "Keithley Parameters", None))
        self.comboBox_7.setAccessibleName(_translate("MainWindow", "4wire", None))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "Off", None))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "On", None))
        self.label_25.setText(_translate("MainWindow", "Compliance [CURRENT]", None))
        self.label_18.setText(_translate("MainWindow", "Four-wire", None))
        self.label_17.setText(_translate("MainWindow", "Terminals", None))
        self.label_19.setText(_translate("MainWindow", "Integration Time", None))
        self.comboBox_6.setAccessibleName(_translate("MainWindow", "route", None))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "Front", None))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "Rear", None))
        self.spinBox.setAccessibleName(_translate("MainWindow", "complianceI", None))
        self.spinBox.setSuffix(_translate("MainWindow", " A", None))
        self.spinBox.setPrefix(_translate("MainWindow", "1 x 10^", None))
        self.comboBox_8.setAccessibleName(_translate("MainWindow", "integrationTime", None))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "0.01", None))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "0.1", None))
        self.comboBox_8.setItemText(2, _translate("MainWindow", "1", None))
        self.comboBox_8.setItemText(3, _translate("MainWindow", "10", None))
        self.label_32.setText(_translate("MainWindow", "Compliance [VOLTAGE]", None))
        self.spinBox_2.setAccessibleName(_translate("MainWindow", "complianceV", None))
        self.spinBox_2.setSuffix(_translate("MainWindow", " V", None))
        self.spinBox_2.setPrefix(_translate("MainWindow", "1 x 10^", None))
        self.label_26.setText(_translate("MainWindow", "Sample time", None))
        self.doubleSpinBox_5.setAccessibleName(_translate("MainWindow", "QCM_sampleTime", None))
        self.doubleSpinBox_5.setSuffix(_translate("MainWindow", " seconds", None))
        self.label_33.setText(_translate("MainWindow", "Serial address", None))
        self.lineEdit_4.setAccessibleName(_translate("MainWindow", "inficonAddr", None))
        self.lineEdit_4.setText(_translate("MainWindow", "/dev/ttyS0", None))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "/dev/", None))
        self.label_29.setText(_translate("MainWindow", "QCM Channels to monitor:", None))
        self.checkBoxQCM1.setAccessibleName(_translate("MainWindow", "QCM1", None))
        self.checkBoxQCM1.setText(_translate("MainWindow", "Channel 1", None))
        self.checkBoxQCM2.setAccessibleName(_translate("MainWindow", "QCM2", None))
        self.checkBoxQCM2.setText(_translate("MainWindow", "Channel 2", None))
        self.checkBoxQCM3.setAccessibleName(_translate("MainWindow", "QCM3", None))
        self.checkBoxQCM3.setText(_translate("MainWindow", "Channel 3", None))
        self.checkBoxQCM4.setAccessibleName(_translate("MainWindow", "QCM4", None))
        self.checkBoxQCM4.setText(_translate("MainWindow", "Channel 4", None))
        self.label_5.setText(_translate("MainWindow", "Feature coming...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Setup", None))
        self.label_4.setText(_translate("MainWindow", "Display:", None))
        self.comboBoxQCM_Display.setAccessibleName(_translate("MainWindow", "QCM_display", None))
        self.comboBoxQCM_Display.setItemText(0, _translate("MainWindow", "Thickness", None))
        self.comboBoxQCM_Display.setItemText(1, _translate("MainWindow", "Rates", None))
        self.pushButton_QCMStart.setText(_translate("MainWindow", "Record", None))
        self.pushButton_QCMStop.setText(_translate("MainWindow", "Stop and Save", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Console:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Deposition Monitor", None))
        self.metalButton.setAccessibleName(_translate("MainWindow", "metalButton", None))
        self.metalButton.setText(_translate("MainWindow", "START METAL EVAP", None))
        self.lcdPressure.setAccessibleName(_translate("MainWindow", "lcdPressure", None))
        self.lcdPower.setAccessibleName(_translate("MainWindow", "lcdPower", None))
        self.label_28.setText(_translate("MainWindow", "Power (%)", None))
        self.label_34.setText(_translate("MainWindow", "Pressure (mBar)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Metal Evaporation", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Console:", None))
        self.stop_button.setText(_translate("MainWindow", "ABORT", None))
        self.start_button.setText(_translate("MainWindow", "START", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Electrical Measurements", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionSave_settings.setText(_translate("MainWindow", "Save settings", None))
        self.actionSave_settings.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionLoad_settings.setText(_translate("MainWindow", "Reload settings", None))
        self.actionLoad_settings.setShortcut(_translate("MainWindow", "Ctrl+R", None))
        self.actionContact_Ross.setText(_translate("MainWindow", "Contact Ross", None))

from src.matplotlibwidget import MatplotlibWidget
